### ISSUE TITLE
宝哥我要请教一下用Java写算法题环境怎么配置的

### ISSUE THREAD

**Issue by lumigj** [wangyanbao666/New_Algo_Java#1]
你怎么运行这些.java文件？还是说你直接在leetcode的console里面不用IDE就直接硬写？

**Comment by wangyanbao666** [comment]
写的时候我还是用idea写的毕竟自动补全太香了，不过我一般懒得写test case就直接在leetcode上运行了

**Comment by lumigj** [comment]
> 写的时候我还是用idea写的毕竟自动补全太香了，不过我一般懒得写test case就直接在leetcode上运行了

用intellij自带的编译器run Java class里面的psvm吗，懂了
